# Generated by Django 4.2.13 on 2026-01-22 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscribedusers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='author_bio',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Yazar Biyografisi'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Kayıt Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_author_approved',
            field=models.BooleanField(default=False, verbose_name='Yazar Onayı'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Premium Üye'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='premium_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Premium Bitiş'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='premium_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Premium Başlangıç'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('reader', 'Okuyucu'), ('author', 'Yazar'), ('admin', 'Admin')], default='reader', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.CharField(blank=True, choices=[('student', 'Öğrenci'), ('academician', 'Akademisyen'), ('researcher', 'Araştırmacı'), ('teacher', 'Öğretmen'), ('doctor', 'Doktor'), ('professor', 'Profesör'), ('writer', 'Yazar'), ('other', 'Diğer')], max_length=20, null=True, verbose_name='Ünvan'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, default='', max_length=600, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('regular', 'Normal'), ('premium', 'Premium'), ('moderator', 'Moderatör')], default='regular', max_length=100),
        ),
    ]
