# Generated by Django 4.2.13 on 2026-01-30 12:34

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_subscribedusers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Kullanıcı",
                "verbose_name_plural": "Kullanıcılar",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="author_bio",
            field=models.TextField(
                blank=True,
                default="",
                max_length=2000,
                verbose_name="Yazar Biyografisi",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="author_title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student", "Öğrenci"),
                    ("academic", "Akademisyen"),
                    ("researcher", "Araştırmacı"),
                    ("writer", "Yazar"),
                    ("professor", "Profesör"),
                    ("doctor", "Doktor"),
                    ("other", "Diğer"),
                ],
                default="writer",
                max_length=20,
                verbose_name="Yazar Ünvanı",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="author_website",
            field=models.URLField(blank=True, verbose_name="Website"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="books_published",
            field=models.IntegerField(
                default=0, verbose_name="Yayınlanan Kitap Sayısı"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_author_approved",
            field=models.BooleanField(
                default=False,
                help_text="Admin tarafından onaylanmış yazar",
                verbose_name="Yazar Onayı",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_premium",
            field=models.BooleanField(default=False, verbose_name="Premium Üye"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="premium_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Premium Bitiş Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="total_readers",
            field=models.IntegerField(default=0, verbose_name="Toplam Okuyucu Sayısı"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_role",
            field=models.CharField(
                choices=[
                    ("reader", "Okuyucu"),
                    ("author", "Yazar"),
                    ("admin", "Admin"),
                ],
                default="reader",
                max_length=20,
                verbose_name="Kullanıcı Rolü",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="description",
            field=models.TextField(
                blank=True, default="", max_length=600, verbose_name="Açıklama"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                default="default/user.jpg",
                upload_to=users.models.CustomUser.image_upload_to,
                verbose_name="Profil Resmi",
            ),
        ),
    ]
