# Generated by Django 4.2.13 on 2026-01-22 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_article_image_articleseries_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Kitap Başlığı')),
                ('slug', models.SlugField(max_length=350, unique=True, verbose_name='Slug')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Alt Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('file', models.FileField(blank=True, null=True, upload_to=main.models.Book.book_upload_to, verbose_name='Kitap Dosyası')),
                ('file_type', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('docx', 'Word (DOCX)'), ('doc', 'Word (DOC)')], max_length=10, verbose_name='Dosya Tipi')),
                ('cover_image', models.ImageField(default='default/book_cover.jpg', upload_to=main.models.Book.cover_upload_to, verbose_name='Kapak Görseli')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('pending', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('published', 'Yayında'), ('rejected', 'Reddedildi')], default='draft', max_length=20, verbose_name='Durum')),
                ('is_processed', models.BooleanField(default=False, help_text='Dosya AI tarafından işlendi mi?', verbose_name='İşlendi mi?')),
                ('ai_summary', models.TextField(blank=True, help_text='AI tarafından oluşturulan özet', verbose_name='AI Özeti')),
                ('has_toc', models.BooleanField(default=False, verbose_name='İçindekiler var mı?')),
                ('view_count', models.IntegerField(default=0, verbose_name='Görüntülenme')),
                ('download_count', models.IntegerField(default=0, verbose_name='İndirilme')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Yayın Tarihi')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='Yayınevi')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ISBN')),
                ('publication_year', models.IntegerField(blank=True, null=True, verbose_name='Yayın Yılı')),
                ('page_count', models.IntegerField(blank=True, null=True, verbose_name='Sayfa Sayısı')),
                ('language', models.CharField(default='Türkçe', max_length=50, verbose_name='Dil')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notları')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Red Nedeni')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'Kitap',
                'verbose_name_plural': 'Kitaplar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='Kategori Slug')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Bölüm Başlığı')),
                ('slug', models.SlugField(max_length=550, verbose_name='Slug')),
                ('content', models.TextField(blank=True, verbose_name='İçerik')),
                ('chapter_number', models.IntegerField(default=1, verbose_name='Bölüm Numarası')),
                ('level', models.IntegerField(default=1, help_text='1: Ana başlık, 2: Alt başlık, vb.', verbose_name='Seviye')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('page_start', models.IntegerField(blank=True, null=True, verbose_name='Başlangıç Sayfası')),
                ('page_end', models.IntegerField(blank=True, null=True, verbose_name='Bitiş Sayfası')),
                ('ai_summary', models.TextField(blank=True, verbose_name='Bölüm Özeti')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='main.book', verbose_name='Kitap')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subchapters', to='main.chapter', verbose_name='Üst Bölüm')),
            ],
            options={
                'verbose_name': 'Bölüm',
                'verbose_name_plural': 'Bölümler',
                'ordering': ['book', 'order', 'chapter_number'],
                'unique_together': {('book', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Librovaai', max_length=100, verbose_name='Site Adı')),
                ('site_description', models.TextField(default='Dijital Kitap Platformu', max_length=500, verbose_name='Site Açıklaması')),
                ('site_keywords', models.CharField(blank=True, max_length=500, verbose_name='SEO Anahtar Kelimeler')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Site Logosu')),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Favicon')),
                ('contact_email', models.EmailField(default='info@librovaai.com', max_length=254, verbose_name='İletişim E-posta')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('contact_address', models.TextField(blank=True, verbose_name='Adres')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('footer_text', models.TextField(default='© 2026 Librovaai. Tüm hakları saklıdır.', max_length=500, verbose_name='Footer Metni')),
                ('footer_about', models.TextField(blank=True, max_length=500, verbose_name='Footer Hakkımızda')),
                ('meta_title', models.CharField(default='Librovaai - Dijital Kitap Platformu', max_length=150, verbose_name='Meta Başlık')),
                ('meta_description', models.TextField(default='AI destekli dijital kitap platformu', max_length=300, verbose_name='Meta Açıklama')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Aktif olduğunda site ziyaretçilere kapatılır', verbose_name='Bakım Modu')),
                ('maintenance_message', models.TextField(default='Şu anda bakımdayız. Kısa süre içinde geri döneceğiz.', max_length=500, verbose_name='Bakım Modu Mesajı')),
                ('default_language', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English'), ('de', 'Deutsch'), ('fr', 'Français')], default='tr', max_length=10, verbose_name='Varsayılan Dil')),
                ('timezone', models.CharField(default='Europe/Istanbul', max_length=50, verbose_name='Zaman Dilimi')),
                ('allow_registration', models.BooleanField(default=True, help_text='Yeni kullanıcı kaydına izin ver', verbose_name='Kayıt İzni')),
                ('allow_comments', models.BooleanField(default=True, help_text='Kitap yorumlarına izin ver', verbose_name='Yorum İzni')),
                ('enable_ai_processing', models.BooleanField(default=False, help_text='AI özet üretimini aktif et', verbose_name='AI İşleme')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
                ('google_site_verification', models.CharField(blank=True, max_length=100, verbose_name='Google Site Verification')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book', verbose_name='Kitap')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chapter', verbose_name='Bölüm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Yer İmi',
                'verbose_name_plural': 'Yer İmleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(related_name='books', to='main.category', verbose_name='Kategoriler'),
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='İlerleme %')),
                ('last_read_at', models.DateTimeField(auto_now=True, verbose_name='Son Okuma')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book', verbose_name='Kitap')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.chapter', verbose_name='Son Okunan Bölüm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Okuma İlerlemesi',
                'verbose_name_plural': 'Okuma İlerlemeleri',
                'ordering': ['-last_read_at'],
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='BookRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Puan')),
                ('review', models.TextField(blank=True, verbose_name='Yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='main.book', verbose_name='Kitap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Değerlendirme',
                'verbose_name_plural': 'Değerlendirmeler',
                'ordering': ['-created_at'],
                'unique_together': {('book', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status', '-created_at'], name='main_book_status_0f1c77_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['slug'], name='main_book_slug_5e5d1f_idx'),
        ),
    ]
