# Generated by Django 4.2.13 on 2026-01-30 11:13

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_article_image_articleseries_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Libraria", max_length=200, verbose_name="Site Adı"
                    ),
                ),
                (
                    "site_description",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Site Açıklaması",
                    ),
                ),
                (
                    "site_keywords",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="SEO Anahtar Kelimeler",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=main.models.SiteSettings.logo_upload_to,
                        verbose_name="Logo",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=main.models.SiteSettings.favicon_upload_to,
                        verbose_name="Favicon",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="İletişim Email",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Telefon"
                    ),
                ),
                (
                    "contact_address",
                    models.TextField(
                        blank=True, default="", max_length=500, verbose_name="Adres"
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, default="", verbose_name="Facebook"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, default="", verbose_name="Twitter/X"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, default="", verbose_name="Instagram"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, default="", verbose_name="LinkedIn"),
                ),
                (
                    "youtube_url",
                    models.URLField(blank=True, default="", verbose_name="YouTube"),
                ),
                (
                    "footer_text",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Footer Metni",
                    ),
                ),
                (
                    "footer_about",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=1000,
                        verbose_name="Footer Hakkımızda",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Meta Title",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Google Analytics ID",
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(default=False, verbose_name="Bakım Modu"),
                ),
                (
                    "maintenance_message",
                    models.TextField(
                        blank=True,
                        default="Site bakımda, lütfen daha sonra tekrar deneyin.",
                        max_length=500,
                        verbose_name="Bakım Modu Mesajı",
                    ),
                ),
                (
                    "default_language",
                    models.CharField(
                        default="tr", max_length=10, verbose_name="Varsayılan Dil"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Europe/Istanbul",
                        max_length=50,
                        verbose_name="Zaman Dilimi",
                    ),
                ),
                (
                    "allow_registration",
                    models.BooleanField(default=True, verbose_name="Kayıt İzni"),
                ),
                (
                    "allow_comments",
                    models.BooleanField(default=True, verbose_name="Yorum İzni"),
                ),
                (
                    "enable_ai_processing",
                    models.BooleanField(default=False, verbose_name="AI İşleme Aktif"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
            ],
            options={
                "verbose_name": "Site Ayarı",
                "verbose_name_plural": "Site Ayarları",
            },
        ),
    ]
