# Generated by Django 4.2.13 on 2026-01-30 12:11

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="banner_button_link_1",
            field=models.CharField(
                blank=True,
                default="#",
                max_length=200,
                verbose_name="Banner Buton Linki 1",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="banner_button_link_2",
            field=models.CharField(
                blank=True,
                default="#",
                max_length=200,
                verbose_name="Banner Buton Linki 2",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="banner_button_link_3",
            field=models.CharField(
                blank=True,
                default="#",
                max_length=200,
                verbose_name="Banner Buton Linki 3",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="banner_button_text_1",
            field=models.CharField(
                blank=True,
                default="Read More",
                max_length=50,
                verbose_name="Banner Buton Metni 1",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="banner_button_text_2",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Banner Buton Metni 2",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="banner_button_text_3",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Banner Buton Metni 3",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="banner_description_1",
            field=models.TextField(
                blank=True, default="", max_length=500, verbose_name="Banner Açıklama 1"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="banner_description_2",
            field=models.TextField(
                blank=True, default="", max_length=500, verbose_name="Banner Açıklama 2"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="banner_description_3",
            field=models.TextField(
                blank=True, default="", max_length=500, verbose_name="Banner Açıklama 3"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="banner_image_1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=main.models.SiteSettings.banner_upload_to,
                verbose_name="Banner Görseli 1",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="banner_image_2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=main.models.SiteSettings.banner_upload_to,
                verbose_name="Banner Görseli 2",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="banner_image_3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=main.models.SiteSettings.banner_upload_to,
                verbose_name="Banner Görseli 3",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="banner_subtitle_1",
            field=models.CharField(
                blank=True,
                default="Discover Your Roots",
                max_length=200,
                verbose_name="Banner Alt Başlık 1",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="banner_subtitle_2",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Banner Alt Başlık 2",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="banner_subtitle_3",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Banner Alt Başlık 3",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="banner_title_1",
            field=models.CharField(
                blank=True,
                default="Online Learning Anytime, Anywhere!",
                max_length=200,
                verbose_name="Banner Başlık 1",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="banner_title_2",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Banner Başlık 2"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="banner_title_3",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Banner Başlık 3"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enable_banner",
            field=models.BooleanField(default=True, verbose_name="Banner/Slider Aktif"),
        ),
    ]
