# Generated by Django 4.2.13 on 2026-01-30 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0006_sitesettings_banner_button_link_1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Kitap Başlığı"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=350, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Kitap hakkında kısa açıklama",
                        max_length=2000,
                        verbose_name="Açıklama",
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        unique=True,
                        verbose_name="ISBN",
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Yayınevi"
                    ),
                ),
                (
                    "language",
                    models.CharField(default="tr", max_length=10, verbose_name="Dil"),
                ),
                (
                    "page_count",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="Sayfa Sayısı"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fiction", "Kurgu"),
                            ("non_fiction", "Kurgu Dışı"),
                            ("science", "Bilim"),
                            ("history", "Tarih"),
                            ("biography", "Biyografi"),
                            ("education", "Eğitim"),
                            ("technology", "Teknoloji"),
                            ("philosophy", "Felsefe"),
                            ("religion", "Din"),
                            ("art", "Sanat"),
                            ("poetry", "Şiir"),
                            ("other", "Diğer"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Virgülle ayırın",
                        max_length=500,
                        verbose_name="Etiketler",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=main.models.Book.cover_upload_to,
                        verbose_name="Kapak Resmi",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=main.models.Book.file_upload_to,
                        verbose_name="Kitap Dosyası (PDF/Word)",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Dosya Tipi"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, default=0, verbose_name="Dosya Boyutu (bytes)"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="AI İşlendi"),
                ),
                (
                    "has_toc",
                    models.BooleanField(default=False, verbose_name="İçindekiler Var"),
                ),
                (
                    "has_summary",
                    models.BooleanField(default=False, verbose_name="Özet Var"),
                ),
                (
                    "processing_error",
                    models.TextField(blank=True, verbose_name="İşleme Hatası"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Taslak"),
                            ("pending", "Onay Bekliyor"),
                            ("approved", "Onaylandı"),
                            ("published", "Yayında"),
                            ("rejected", "Reddedildi"),
                            ("archived", "Arşivlendi"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Red Nedeni"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Yayın Tarihi"
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(default=0, verbose_name="Görüntülenme"),
                ),
                (
                    "download_count",
                    models.IntegerField(default=0, verbose_name="İndirme"),
                ),
                (
                    "rating_count",
                    models.IntegerField(default=0, verbose_name="Değerlendirme Sayısı"),
                ),
                (
                    "rating_average",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        verbose_name="Ortalama Puan",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_books",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Onaylayan Admin",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yazar",
                    ),
                ),
                (
                    "co_authors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="co_authored_books",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ortak Yazarlar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kitap",
                "verbose_name_plural": "Kitaplar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=500, verbose_name="Bölüm Başlığı"),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=550, verbose_name="Slug"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Bölüm sırası", verbose_name="Sıra"
                    ),
                ),
                (
                    "content",
                    tinymce.models.HTMLField(blank=True, verbose_name="İçerik"),
                ),
                (
                    "page_start",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="Başlangıç Sayfası"
                    ),
                ),
                (
                    "page_end",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="Bitiş Sayfası"
                    ),
                ),
                (
                    "word_count",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="Kelime Sayısı"
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=1,
                        help_text="1=Ana Bölüm, 2=Alt Bölüm",
                        verbose_name="Seviye",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="main.book",
                        verbose_name="Kitap",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subchapters",
                        to="main.chapter",
                        verbose_name="Üst Bölüm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bölüm",
                "verbose_name_plural": "Bölümler",
                "ordering": ["book", "order"],
                "unique_together": {("book", "order")},
            },
        ),
        migrations.CreateModel(
            name="BookSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary_type",
                    models.CharField(
                        choices=[
                            ("short", "Kısa Özet"),
                            ("medium", "Orta Özet"),
                            ("detailed", "Detaylı Özet"),
                            ("chapter", "Bölüm Özeti"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Özet Tipi",
                    ),
                ),
                ("content", models.TextField(verbose_name="Özet İçeriği")),
                (
                    "generated_by",
                    models.CharField(
                        default="OpenAI",
                        help_text="OpenAI, Gemini, vb.",
                        max_length=50,
                        verbose_name="Oluşturan AI",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "token_count",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="Token Sayısı"
                    ),
                ),
                (
                    "is_premium_only",
                    models.BooleanField(default=True, verbose_name="Sadece Premium"),
                ),
                (
                    "word_count",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="Kelime Sayısı"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="main.book",
                        verbose_name="Kitap",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="main.chapter",
                        verbose_name="Bölüm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kitap Özeti",
                "verbose_name_plural": "Kitap Özetleri",
                "unique_together": {("book", "summary_type", "chapter")},
            },
        ),
    ]
