# Generated by Django 4.2.13 on 2026-01-30 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_book_chapter_booksummary"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Kategori Adı"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=120, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Açıklama"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Örn: fa-book, fa-science",
                        max_length=50,
                        verbose_name="İkon (Font Awesome)",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3498db",
                        help_text="Hex renk kodu (örn: #3498db)",
                        max_length=7,
                        verbose_name="Renk Kodu",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sıralama")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "book_count",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="Kitap Sayısı"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
            ],
            options={
                "verbose_name": "Kitap Kategorisi",
                "verbose_name_plural": "Kitap Kategorileri",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="main.bookcategory",
                verbose_name="Kategori",
            ),
        ),
    ]
